spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  #  sql:
  #    init:
  #      mode: always
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret-key: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
  access-token-expiration-time: 1800000

basket:
  timeout: 5
  time-unit: MINUTES